# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('population', models.DecimalField(decimal_places=5, max_digits=10)),
                ('aggregate', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('export', models.CharField(max_length=200)),
            ],
        ),
    ]
