# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 00:27
from __future__ import unicode_literals
import csv
from django.db import migrations


def load_data_csv(apps, schema_editor):
    Countries = apps.get_model("countries", "Countries")
    with open('countries/countries.csv', 'r') as csvfile:
        fields = {"fieldnames": ("name", "capital", "population", "aggregate", "status", "language", "export")}
        reader = csv.DictReader(csvfile, **fields)
        for row in reader:
            c = Countries(**row)
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_csv),
    ]
