# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
    ]
